# Generated by Django 3.2.19 on 2023-11-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0359_team_external_data_workspace_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginconfig",
            name="deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="description",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="pluginconfig",
            name="name",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
